### ISSUE TITLE
After HA update this integration is broken

### ISSUE THREAD

**Issue by spider7611** [bruxy70/Garbage-Collection#479]
### Before you submit a new bug report, please check that

- [x] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [x] I'm running the newest version of Garbage Collection, or the next pre-release.
- [x] I have enabled debug logging for my installation.

### Describe the bug

Home Assistant update to 2025.6.0 this integration is broken. Can you fix this? TY!

### Configuration

```JSON
n
```

### Debug logs

```shell
n
```

**Comment by adorobis** [comment]
Same here. Errors in the log:
```
2025-06-11 23:30:04.427 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Selective for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-11 23:30:04.431 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mixed for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

**Comment by prolife86** [comment]
The error:

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 22:10:49 (3 occurrences)
Last logged: 22:10:49

Error setting up entry Grijze Container for garbage_collection
Error setting up entry Groene Contrainer for garbage_collection
Error setting up entry Oud papier for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by prolife86** [comment]
Per the debugfile:

2025-06-12 22:10:48.978 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-06-12 22:10:49.216 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.growatt_total_monthly (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using state class 'total_increasing' which is impossible considering device class ('power') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2025-06-12 22:10:49.217 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.growatt_total_yearly (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using state class 'total_increasing' which is impossible considering device class ('power') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2025-06-12 22:10:49.616 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Grijze Container for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 22:10:49.620 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Groene Contrainer for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 22:10:49.621 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Oud papier for garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garbage_collection/__init__.py", line 230, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 22:10:50.288 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'fontawesome' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/fontawesome/main.js", "/config/custom_components/fontawesome/main.js", True)])` at custom_components/fontawesome/__init__.py, line 50: hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please report it to the author of the 'fontawesome' custom integration

**Comment by adorobis** [comment]
Just keep in mind that this repo is not maintained anymore as announced 2 years ago...

**Comment by prolife86** [comment]
> Just keep in mind that this repo is not maintained anymore as announced 2 years ago...

Thanks for the pointer!
I see the [fix ](https://github.com/bruxy70/Garbage-Collection/pull/476)for this also has been pending for quite some time.
(FYI: entered the changes manually, did not work).
Time to find another way to have my garbage present in HA.

**Comment by adorobis** [comment]
> Time to find another way to have my garbage present in HA.

I'll be switching just to use local calendar and some automations based on that. Should be sufficient for my schedules and not relying on custom integrations.

**Comment by djlukas7** [comment]
This [fix](https://github.com/bruxy70/Garbage-Collection/pull/476) work great for me. I will apply this change using the File Editor in Home Assistant.

**Comment by B0ndo2** [comment]
Here is the cause of the issue, removal of hass.config_entries.async_forward_entry_setup in Home Assistant 2025.6. https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by adorobis** [comment]
> Here is the cause of the issue, removal of hass.config_entries.async_forward_entry_setup in Home Assistant 2025.6. https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

<img width="1006" height="187" alt="Image" src="https://github.com/user-attachments/assets/a8504ed0-2b04-47b1-af32-97bb7bb08a28" />
